
# 電信管制射頻器材型式認證證明 

證照字號：型式字第AJ號 

一、申 請 者：永冠企業社 

二、地址：苗栗縣竹南鎮竹興里勤興街37巷3弄1號1樓 

三、製造廠商：深圳市四舍五入科技有限公司 

四、器材名稱：原子閘鐘藍牙音響 

五、廠牌：永冠 

六、型號：X11 

七、發射功率(電場強度)：85.07 dBuV/m @3m (Peak) 

八、工作頻率：2402 MHz ~ 2480 MHz 

九、審驗日期：112年07月05日 

十、審驗合格標籤式樣：CCAJ23LP24A0T2 

十一、警語或標示要求：附件一 

十二、特殊記載事項：附件二 

![](images/0_0.jpg)

 

說明： 

1. 本中心係經國家通訊傳播委員會委託之驗證機構(機構地址：高雄市路竹區路科一路3號、電話：07-6955001)，核發本型式認證證明。 

2. 請依上列型號、標籤式樣於電信管制射頻器材本體明顯處標示其型號及審驗合格標籤，並於包裝盒標示國家通訊傳播委員會標章。但最終產品應於本體明顯處標示最終產品型號及上列標籤式樣，並於包裝盒標示國家通訊傳播委員會標章。 

3. 本器材之製造、輸入或販賣須遵守電信管理法相關規定。 

備註： 

1. 本器材符合109年低功率射頻器材技術規範LP0002(4.10.2)之規定。 

2. 本器材之審驗範圍僅限無線射頻硬體功能，不及於器材之資通安全檢測。 

3. Type-C 充電線：廠牌：永冠，型號：X11。 

4. 音源線：廠牌：永冠，型號：X11。 

5. 天線：型態：PCB 天線，增益：-0.58 dBi。廠牌：ZHUHAI JIELI，型號：2.4G ANT。 

中華民國 1 1 2 年 0 7 月 0 5 日

<--- Page Split --->

附件一：(器材本體、使用手冊、外包裝盒等應遵守下列標示要求)  

1. 於本體明顯處標示審驗合格標籤或符合性聲明標籤及其型號，並於包裝盒標示主管機關標章。最終產品應於本體明顯處標示非隨插即用射頻模組（組件）之審驗合格標籤及最終產品型號，並於包裝盒標示主管機關標章。  

2. 依主管機關或相關技術規範規定於指定位置標示正確中文警語。  

3. 電信管制射頻器材內建螢幕或須連接螢幕始能操作者，標示審驗合格標籤或符合性聲明標籤、型號或正確中文警語標示得以螢幕顯示代之，並於包裝盒、使用手冊或說明書載明操作方式。  

4. 於網際網路販賣電信管制射頻器材者，應於該網際網路網頁標示其型號及審驗合格標籤或符合性聲明標籤資訊。但最終產品得僅標示其型號及其組裝之非隨插即用射頻模組（組件）之審驗合格標籤資訊。  

5. 使用手冊應標示下列資訊：  

(1) 所有控制、調整及開關之使用方法。(2) 取得審驗證明之低功率射頻器材，非經核准，公司、商號或使用者均不得擅自變更頻率、加大功率或變更原設計之特性及功能。低功率射頻器材之使用不得影響飛航安全及干擾合法通信；經發現有干擾現象時，應立即停用，並改善至無干擾時方得繼續使用。前述合法通信，指依電信管理法規定作業之無線電通信。低功率射頻器材須忍受合法通信或工業、科學及醫療用電波輻射性電機設備之干擾。  

## 附件二：  

1. 取得審驗證明之電信管制射頻器材或非隨插即用射頻模組（組件），變更原申請者、廠牌、型號、硬體、射頻功能、外觀、顏色、材質、電源供應方式、配件或天線時，除本辦法另有規定外，應重新申請審驗。  

2. 取得型式認證證明、符合性聲明證明或簡易符合性聲明證明者，應妥善保管申請審驗之電信管制射頻器材或非隨插即用射頻模組（組件）、外接電源、配件、外接天線、與檢驗報告或測試報告相符之測試治具及與檢驗報告或測試報告使用相同版本之測試軟體至該器材停止生產或停止輸入後五年。  

3. 取得型式認證證明或符合性聲明證明者得授權他人於同廠牌同型號之電信管制射頻器材或非隨插即用射頻模組（組件）使用審驗合格標籤或符合性聲明標籤，應由取得審驗證明者於主管機關指定網站登錄或委託原驗證機關（構）登錄。  

4. 以取得審驗證明之完全射頻模組（組件）組裝成完全最終產品後，取得該完全射頻模組（組件）之審驗證明者，應於該完全最終產品販賣前，檢附標註完全最終產品廠牌、型號及外觀照片之電子檔案，向原驗證機關（構）登錄。以完全射頻模組（組件）取得審驗證明者，授權他人使用其審驗合格標籤，於完全射頻模組（組件）組裝成完全最終產品後，取得該完全射頻模組（組件）之審驗證明者應檢附標註完全最終產品廠牌、型號及外觀照片之電子檔案，向原驗證機關（構）登錄。  

5. 若器材與隨貨配件經抽驗不合格者，將廢止審驗證明；若變更隨貨配件（或原不提供隨貨配件），器材及隨貨配件經抽驗不合格者，將廢止審驗證明；若變更隨貨配件，器材及隨貨配件經抽驗合格者，將通知限期重新申請審驗，逾期未重新申請審驗者，將廢止審驗證明。  

6. 本器材、本模組或其組裝之最終產品，與併同販賣之外接電源、配件或外接天線，應符合相關審驗辦法及低功率射頻器材技術規範規定。若本器材、模組或其組裝之最終產品，與併同販賣之外接電源、配件或外接天線，經抽驗不合格者，將廢止本器材或本模組型式認證證明/簡易符合性聲明證明。  

7. 電信管制射頻器材或非隨插即用射頻模組（組件）之取得審驗證明者，於相關技術規範修正，並限期重新申請審驗時，應申請重新審驗，並得使用原審驗合格標籤或符合性聲明標籤。  

## 證明號碼：CCAJ23LP24A0T2  

中華民國 1 1 2 年 0 7 月 0 5 日

<--- Page Split --->
