<|ref|>title<|/ref|><|det|>[[365, 89, 635, 115]]<|/det|>
臺北市政府 函  

<|ref|>text<|/ref|><|det|>[[123, 160, 165, 179]]<|/det|>
110  

<|ref|>text<|/ref|><|det|>[[125, 182, 450, 203]]<|/det|>
臺北市信義區松德路161號19樓  

<|ref|>text<|/ref|><|det|>[[125, 207, 450, 229]]<|/det|>
受文者：莫克國際有限公司  

<|ref|>text<|/ref|><|det|>[[123, 254, 490, 293]]<|/det|>
發文日期：中華民國113年12月19日發文字號：府產業商字第11355531230號  

<|ref|>text<|/ref|><|det|>[[123, 294, 262, 311]]<|/det|>
速別：普通件  

<|ref|>text<|/ref|><|det|>[[123, 312, 338, 329]]<|/det|>
密等及解密條件：普通  

<|ref|>text<|/ref|><|det|>[[123, 330, 437, 349]]<|/det|>
附件：规費收據暨變更登記表1份  

<|ref|>text<|/ref|><|det|>[[125, 362, 860, 416]]<|/det|>
主旨：貴公司（統一編號：54347486）申請增資、增加所營事業、董事地址變更、修正章程變更登記，准予登記。並請詳閱說明相關事項，以保障公司權益，請查照。  

<|ref|>text<|/ref|><|det|>[[123, 418, 187, 436]]<|/det|>
說明：  

<|ref|>text<|/ref|><|det|>[[144, 433, 860, 470]]<|/det|>
一、依公司法辦理兼復貴公司113年11月25日申請書、113年12月3日、113年12月12日及113年12月18日補正書件。  

<|ref|>text<|/ref|><|det|>[[144, 467, 858, 519]]<|/det|>
二、處分相對人名：莫克國際有限公司（代表人姓名：呂子毓、身分證照號碼：F22525\*\*\*\*）、公司所在地：臺北市信義區松德路161號19樓。  

<|ref|>text<|/ref|><|det|>[[144, 516, 844, 567]]<|/det|>
三、貴公司填載查詢之營業場所（臺北市信義區松德路161號19樓）及營業項目「F206050寵物食品及其用品零售業」（限辦），經本府「營業場所預先查詢服務平台」協助查詢結果：  

<|ref|>text<|/ref|><|det|>[[192, 565, 858, 633]]<|/det|>
（一）都市發展局：符合，1. 僅限19樓使用，不得佔用陽臺、兩遮及其他樓層。2. 樓地板面積限於81.83平方公尺以下。3. 現場僅限作辦公室使用，不得專為貯藏、展示、製造、加工、批發、零售、物流等場所使用，且現場不得貯藏機具。  

<|ref|>text<|/ref|><|det|>[[192, 630, 857, 749]]<|/det|>
（二）建築管理工程處：符合規定，依建築物使用類組及變更使用辦法係屬同類組G-2、依使用執照原核准平面圖說範圍使用，不得擴大範圍使用！現場僅限辦公室使用，不得為貯藏、展示、製造、加工、批發、零售、物流等場所使用，且現場不得貯藏機具。申請門牌含第（19～20）層，建議辦理分戶，僅限19樓層使用，不得占用其他樓層。申請人若為房屋承租人，請逕洽所有權人揭露房屋是否有特殊情況，以免衍生額外之私權糾紛。  

<|ref|>text<|/ref|><|det|>[[144, 746, 622, 764]]<|/det|>
四、檢附規費收據暨變更登記表1份，請查收。  

<|ref|>text<|/ref|><|det|>[[144, 761, 857, 880]]<|/det|>
五、公司營業項目：D401010熱能供應業、F106020日常用品批發業、F106060寵物食品及其用品批發業、F109070文教、樂器、育樂用品批發業、F206020日常用品零售業、F206050寵物食品及其用品零售業、F209060文教、樂器、育樂用品零售業、F299990其他零售業、F399040無店面零售業、F401010國際貿易業、F601010智慧財產權業、ZZ99999除許可業務外，得經營法令非禁止或限制之業務。  

<|ref|>text<|/ref|><|det|>[[144, 876, 857, 897]]<|/det|>
六、對本行政處分如有不服，請依訴願法第14條及第58條規定，自行

<--- Page Split --->
<|ref|>text<|/ref|><|det|>[[197, 90, 864, 148]]<|/det|>
政處分書達到之次日起30日內, 繕具訴願書, 向本府遞送 (以實際收受訴願書之日期為準, 而非投郵日), 並將副本抄送經濟部 (地址: 臺北市中正區福州街15號)。  

<|ref|>text<|/ref|><|det|>[[128, 176, 338, 210]]<|/det|>
正本: 莫克國際有限公司副本:  

<|ref|>title<|/ref|><|det|>[[128, 210, 800, 315]]<|/det|>
# 市长蒋萬安  

<|ref|>text<|/ref|><|det|>[[262, 342, 572, 362]]<|/det|>
本案依分層負責規定授權人員決行

<--- Page Split --->
