<|ref|>image<|/ref|><|det|>[[72, 150, 200, 300]]<|/det|>
 

<|ref|>text<|/ref|><|det|>[[240, 180, 590, 290]]<|/det|>
中華民國國民身分證 

<|ref|>text<|/ref|><|det|>[[87, 450, 585, 540]]<|/det|>
姓名 魏誌良 

<|ref|>text<|/ref|><|det|>[[87, 592, 568, 705]]<|/det|>
出生 民國 81 年 3 月 1 日
年月日 

<|ref|>text<|/ref|><|det|>[[87, 746, 555, 811]]<|/det|>
發證日期 民國112年9月7日(桃市)換發 

<|ref|>image<|/ref|><|det|>[[592, 156, 940, 840]]<|/det|>

<--- Page Split --->
