<|ref|>sub_title<|/ref|><|det|>[[444, 50, 564, 68]]<|/det|>
## 權利人聲明書  

<|ref|>text<|/ref|><|det|>[[72, 79, 933, 118]]<|/det|>
本公司/本人兹此聲明及保證本公司/本人以下陳述均為真實，如有任何不實，本公司/本人願負擔一切責任並賠償貴公司或其他第三人因此所致之一切損害：  

<|ref|>text<|/ref|><|det|>[[72, 118, 925, 234]]<|/det|>
一、本公司/本人是智慧財產權/NCC&BSMI字號持有人，或經智慧財產權人/NCC&BSMI字號持有人授權提出檢舉之人（以下稱權利人）。二、本公司/本人同意貴公司得將以下聯絡資訊提供予被檢舉之賣家，作為商品因本公司/本人檢舉而下架之賣家與本公司/本人連繫之用。三、本公司/本人就本件檢舉及後續檢舉事宜，授權下列之聯絡人代表本公司/本人提出檢舉暨相關文件。  

<|ref|>text<|/ref|><|det|>[[72, 248, 503, 267]]<|/det|>
此致 新加坡商蝦皮娛樂電商有限公司台灣分公司  

<|ref|>text<|/ref|><|det|>[[72, 281, 405, 301]]<|/det|>
權利人名/姓名：莫克國際有限公司  

<|ref|>text<|/ref|><|det|>[[72, 304, 400, 325]]<|/det|>
統一編號/身分證字號：54491486  

<|ref|>text<|/ref|><|det|>[[72, 329, 422, 350]]<|/det|>
地址：臺北市信義區松德路161號19楼  

<|ref|>text<|/ref|><|det|>[[72, 351, 230, 375]]<|/det|>
聯絡人：  

<|ref|>text<|/ref|><|det|>[[72, 377, 255, 397]]<|/det|>
聯絡人職：  

<|ref|>text<|/ref|><|det|>[[72, 398, 411, 419]]<|/det|>
聯絡電話：62- 23960916  

<|ref|>text<|/ref|><|det|>[[72, 424, 338, 444]]<|/det|>
傳真號碼：02- 23960915  

<|ref|>text<|/ref|><|det|>[[72, 450, 180, 468]]<|/det|>
email 信箱：  

<|ref|>text<|/ref|><|det|>[[231, 448, 512, 469]]<|/det|>
Con/taot@work.com  

<|ref|>text<|/ref|><|det|>[[70, 483, 916, 525]]<|/det|>
以上資料請確實填寫，聯絡人得填寫2至3位處理專人，蝦皮購物將直接留存您提供的聯絡電話及e- mail信箱於系統内，以利日後侵權申訴流程順利進行。  

<|ref|>image<|/ref|><|det|>[[310, 525, 690, 625]]<|/det|>  

<|ref|>text<|/ref|><|det|>[[70, 604, 440, 621]]<|/det|>
請於此加蓋權利人登記大小章  

<|ref|>text<|/ref|><|det|>[[70, 624, 163, 637]]<|/det|>
應檢附文件：  

<|ref|>text<|/ref|><|det|>[[70, 636, 916, 668]]<|/det|>
1. 權利人如為公司，須提供公司設立或變更登記事項表影本加蓋公司大小章；權利人如為自然人，須提供身分證正面影本。  

<|ref|>text<|/ref|><|det|>[[70, 668, 201, 683]]<|/det|>
2. 權利證明文件：  

<|ref|>text<|/ref|><|det|>[[90, 684, 680, 765]]<|/det|>
a.商標權：中華民國商標註冊證影本。b.著作權：刊登商品抄襲的原有著作權文字/圖片官網連結、原始圖檔比對等。c.專利權：中華民國專利證書影本(如條新型專利，請同時提供新型專利技術報告)。d.NCC字號：電信管制射頻器材型式認證證明或電信管制射頻器材簡易符合性聲明e.BSMI字號：商品檢驗標識證書等相關文件  

<|ref|>text<|/ref|><|det|>[[70, 767, 378, 782]]<|/det|>
3. 被授權提出檢舉之人須提供授權書影本。  

<|ref|>text<|/ref|><|det|>[[70, 792, 163, 805]]<|/det|>
隱私權政策：  

<|ref|>text<|/ref|><|det|>[[70, 803, 928, 875]]<|/det|>
當您依據蝦皮購物服務條款及本辦法規定提出侵權通知及/或檢舉申訴，即視為您已詳閱蝦皮購物（即新加坡商蝦皮娛樂電商有限公司台灣分公司）隱私權政策，並同意Shopee得依其適用按該政策規定，基於侵權通知、檢舉申訴、受通知人/被檢舉人聯繫、稽核調查及案件管理等事宜蒐集、處理或利用您的個人資料。您得依據個人資料保護法及隱私權政策規定向Shopee請求查詢、複製、補充更正、停止蒐集處理利用或刪除您的個人資料，亦得選擇不提供個人資料，惟您的侵權通知、檢舉或申訴等將因程序未完成而視為不成立。  

<|ref|>text<|/ref|><|det|>[[70, 872, 920, 903]]<|/det|>
權利人對提出相關文件涉及之個人資料，請參考智慧財產權侵權通知辦法內所載之蝦皮購物隱私權政策：https://help.shopee.tw/portal/article/77314?previousPage=other%20Articles

<--- Page Split --->
