
# 新加坡商蝦皮娛樂電商有限公司台灣分公司202503代收轉付開立發票對帳單  

# 對帳發票訂在虛線之下  

<table><tr><td>蝦皮使用者帳號/會員編號</td><td>bicoobabyshop/86918496</td></tr><tr><td>銷帳序號</td><td>202503</td></tr><tr><td>對帳區間</td><td>2025/03/01 - 2025/03/31</td></tr><tr><td>發票收件截止日(遇假日順延)</td><td>2025/04/18</td></tr><tr><td>發票寄送收件人/發票寄送地址</td><td>蝦皮購物帳務部/100台北市中正區八德路一段55號4樓</td></tr></table>  

※訂單彙總明細 詳細帳務明細請合併以下「附件一」與「我的進帳報表」(可點此下載，路徑：蝦皮賣家中心→我的進帳→已撥款→搜尋對帳區間→匯出報表)核對  

<table><tr><td>項目</td><td>金額</td></tr><tr><td>買家支付商品金額【A】(商品原價+賣場商品促銷折扣)</td><td>1,380</td></tr><tr><td>買家支付運費金額【B】</td><td>45</td></tr><tr><td>買家退款金額【C】</td><td>0</td></tr><tr><td>賣場優惠券【D】</td><td>0</td></tr><tr><td>合計總金額(核至進帳報表)</td><td>1,425</td></tr><tr><td>上月協議退款訂單扣除金額【E】</td><td>-0</td></tr><tr><td>非當月個案調整【F】</td><td>-0</td></tr><tr><td>銷售金額(未稅)</td><td>NT$1,357</td></tr><tr><td>營業稅(未稅金額*5%)</td><td>NT$68</td></tr><tr><td>貴司應開立發票金額(含稅)【A+B+C+D+E+F】</td><td>NT$1,425</td></tr></table>  

※服務費用一筆訂單2元(由蝦皮開立發票)  

<table><tr><td>代收轉付開立發票筆數</td><td>服務費用總金額</td></tr><tr><td>1</td><td>2</td></tr></table>  

※提供發票結算應注意事項  

1. 若為開立紙本發票賣家(手寫發票/收銀機統一發票/電子計算機統一發票/等)請協助將【此對帳單用印後】連同【發票】，以掛號或快遞方式寄至【收件人：蝦皮購物帳務部/地址：100台北市中正區八德路一段55號4樓】。  

2. 若為開立電子發票賣家，請直接於【電子發票賣家資訊回傳表單】(可點此連結)回傳您開立的發票資訊，並勾選表示確認及同意對帳單內容，即無須再email回傳用印後對帳單與發票。  

3. 若為透過蝦皮與開發合作的電子發票平台開立賣家，請直接於【開發電子發票平台】(可點此連結)開立發票，並勾選表示確認及同意對帳單內容，即無須再email回傳用印後對帳單與發票。  

4. 發票開立資訊如下：  

(1)【品名】商品一批；【抬頭】新加坡商蝦皮娛樂電商有限公司台灣分公司；【統編】56801904。(2)發票開立日期可為對帳月份最後一天或開立當月日期(例：1月代收轉付開立發票請開立1/31或2月日期)。  

5. 服務費用：  

(1)【服務費用發票開立日】2025/04/25；【服務費用錢包扣款日(遇假日順延作業)】2025/04/25。  

6. 上月協議退款訂單扣除金額【E】：  

因協議部分退款訂單系統仍會撥款整筆訂單之蝦皮折價券、蝦幣等金額予賣家，故將暫由人工於每月扣除上月協議部分退款之訂單應扣除金額。  

相關報表明細已寄送至貴司財務對帳窗口信箱，再請貴司留意收件並依對帳單上之【貴司應開立發票金額】開立發票予蝦皮即可。  

7. 非當月個案調整【F】：  

此訂單金額為2025/02月以前已結算的發票，遇買家有訂單完成後要求個案退款並扣除錢包之情況，於本月應開立發  

票金額中淨額扣除，明細請詳附件一「欄位：對帳月份」為2025/02月以前之訂單。  

8. 個案調整：若確認附件一列示之明細無誤，則無須印出寄回；如有【線下】個案撥退款情形，再請將訂單資訊填入附件一。  

若對帳單與「我的進帳報表」金額不符或其他帳務問題，請洽台灣跨境蝦皮聊聊帳號「/客戶經理」，謝謝！

<--- Page Split --->
