
November 22,2024  

## LETTER OF AUTHORIZATION  

This letter serves as formal authorization by Canva Pty Ltd (hereafter referred to as "Canva") to Mullins Lawyers Pty Ltd (hereafter referred to as "Mullins Lawyers") to act on our behalf in relation to the protection and enforcement of Canva's intellectual property rights in Taiwan.  

We hereby authorize Mullins Lawyers to take all necessary actions, including but not limited to: takedown requests, reporting and complaints, litigation and any other necessary actions  

This authorization is valid until further notice, unless revoked in writing by Canva Pty Ltd. Mullins Lawyers is authorized to represent Canva in all legal matters pertaining to the protection of Canva's intellectual property rights within Taiwan's jurisdiction.  

Please do not hesitate to contact us if further information or clarification is needed.  

Sincerely,  

![](images/0_0.jpg)
  

Natalie Ward  Natalie.Ward@canva.com  IP Protection Department  CANVA PTY LTD  Level 6, 110 Kippax Street,  Surry Hills, NSW 2010,  Australia

<--- Page Split --->
